jupyter:
  build: ./jupyter
  ports:
    - "0.0.0.0:8889:8888"
    - "0.0.0.0:6007:6006"
  volumes:
    - ./libs:/home/ds/notebooks/libs
    - ./jupyter:/home/ds/notebooks
    - ./jupyter/jupyter:/home/ds/.jupyter
  restart: always
  #command: sh spiders.sh 5
  environment:
    - MONGO_HOST=MONGO_HOST
    - MONGO_PORT=MONGO_PORT
    - MONGO_USER=MONGO_USER
    - MONGO_PASS=MONGO_PASS
    - MONGO_COLL=MONGO_COLL
    - MONGO_DATABASE=MONGO_DATABASE

#Web
web:
  build: ./web
  ports:
    - "0.0.0.0:8080:8080"
  volumes:
    - ./web:/usr/src/web
  command: npm start



#Servidor
server:
  build: ./server
  ports:
    - "0.0.0.0:8890:6666"
  volumes:
    - ./libs:/opt/libs
    - ./server:/opt
  command: python -u /opt/runRest.py
  environment:
    - MONGO_HOST=MONGO_HOST
    - MONGO_PORT=MONGO_PORT
    - MONGO_USER=MONGO_USER
    - MONGO_PASS=MONGO_PASS
    - MONGO_COLL=MONGO_COLL
    - MONGO_DATABASE=MONGO_DATABASE
