jupyter:
  build: ./jupyter
  ports:
    - "0.0.0.0:8889:8888"
    - "0.0.0.0:6007:6006"
  volumes:
    - ./libs:/home/ds/notebooks/libs
    - ./jupyter:/home/ds/notebooks
    - ./jupyter/jupyter:/home/ds/.jupyter
  restart: always
  #command: sh spiders.sh 5
  environment:
    - MONGO_HOST=ds021166.mlab.com
    - MONGO_PORT=21166
    - MONGO_USER=webir-user
    - MONGO_PASS=2qdCWrShyzNSpsV
    - MONGO_COLL=api-data
    - MONGO_DATABASE=webir-2016

#Web
web:
  build: ./web
  ports:
    - "0.0.0.0:8080:8080"
  volumes:
    - ./web:/usr/src/web
  command: npm start



#Servidor
server:
  build: ./server
  ports:
    - "0.0.0.0:8890:6666"
  volumes:
    - ./libs:/opt/libs
    - ./server:/opt
  command: python -u /opt/runRest.py
  environment:
    - MONGO_HOST=ds021166.mlab.com
    - MONGO_PORT=21166
    - MONGO_USER=webir-user
    - MONGO_PASS=2qdCWrShyzNSpsV
    - MONGO_COLL=api-data
    - MONGO_DATABASE=webir-2016
